# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: false
    indentSize: 2
    continuationIndentSize: 8
  ParameterListWrapping:
    active: false
    indentSize: 8

style:
  ReturnCount:
    active: false
  MagicNumber:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

complexity:
  LongMethod:
    threshold: 80

exceptions:
  SwallowedException:
    active: false
