# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: false
    indentSize: 2
    continuationIndentSize: 2
  ParameterListWrapping:
    active: false
    indentSize: 2

style:
  ReturnCount:
    active: false
  MagicNumber:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
